### ISSUE TITLE
运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下

### ISSUE THREAD

**Issue by Hongboo-Li** [17-Ranger/VCM_DSSLIC#1]

**Comment by Hongboo-Li** [comment]
在settings文件夹下面的json文件里面"pkl_path"，运行demo.sh时需要使用到

**Comment by Hongboo-Li** [comment]
并不像readme所说的运行demo.sh自动生成到output

**Comment by 17-Ranger** [comment]
您好，我已经毕业不太方便上服务器下载模型文件了，您可以自己训一个版本，训起来很快




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月18日(星期四) 晚上9:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)





 
并不像readme所说的运行demo.sh自动生成到output

**Comment by Hongboo-Li** [comment]
不好意思，有些问题还想向你请教一下，下面是我训练的配置文件
_BASE_: "../Base-RCNN-FPN-VCM.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "/data-8T/lhb/VCM_DSSLIC/models/model_final_2d9806.pkl"

  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
SOLVER:
  STEPS: (80000, 110000)
  MAX_ITER: 120000

INPUT:
 MIN_SIZE_TRAIN: (576, 576)
 MIN_SIZE_TEST: 576
我用这个配置训练出来的模型依次对35，37，39，41，43，45进行实例分割的精度测试，但是测试结果比较低，依次为0.60，0.52，0.50，0.49，0.43，0.27.我想请问一下模型训练是否有一些问题？不进行压缩的时候在5k张openimagev6数据集上的测试结果是0.82，但是压缩之后得出来的结果很差，远远达不到论文的精度

**Comment by Hongboo-Li** [comment]
我每个<QP>.json文件里面的pkl都是训练出来最后保存的模型文件

**Comment by 17-Ranger** [comment]
您好，如果是没加RHFC网络单纯用mask rcnn初始权重有0.82，但是加了RHFC网络就性能很差的话，我建议首先检查下训练推理模型是否一致，也就是detectron里的rcnn.py和测试的eval.py，不一致的话测试脚本会有警告；其次我看你的resize有好几行，确保test的时候是800（文章里的576是trick，先调试没问题了再自己看着改）；最后印象中segmentation收敛速度比detection要慢挺多，最好用tensorboard看看训练有没有收敛。
如果是添加了RHFC网络后直接推理有0.82但是使用vvc压缩了就性能很差，那就检查下ffmpeg转换和vvc压缩的问题，可以测一下ffmpeg转换前后psnr是不是100，然后vvc检查下output。不过如果这部分没做修改的话应该也没问题。






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月25日(星期一) 晚上8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)





 
不好意思，有些问题还想向你请教一下，下面是我训练的配置文件
 BASE: "../Base-RCNN-FPN-VCM.yaml"
 MODEL:
 MASK_ON: True
 
WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
 
WEIGHTS: "/data-8T/lhb/VCM_DSSLIC/models/model_final_2d9806.pkl"
 
WEIGHTS: "/data-8T/lhb/VCM_DSSLIC/models/model_final_576_3.pth"
 
PIXEL_STD: [57.375, 57.120, 58.395]
 RESNETS:
 STRIDE_IN_1X1: False  # this is a C2 model
 NUM_GROUPS: 32
 WIDTH_PER_GROUP: 8
 DEPTH: 101
 SOLVER:
 STEPS: (80000, 110000)
 MAX_ITER: 120000
 
INPUT:
 
MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
 
MIN_SIZE_TRAIN: (32, 32)
 
MIN_SIZE_TRAIN: (576, 576)
 
MIN_SIZE_TRAIN: (416, 416)
 
MIN_SIZE_TRAIN: (352, 352)
 
MIN_SIZE_TEST: 576
 
MIN_SIZE_TEST: 800
 
MIN_SIZE_TEST: 416
 
我用这个配置训练出来的模型依次对35，37，39，41，43，45进行实例分割的精度测试，但是测试结果比较低，依次为0.60，0.52，0.50，0.49，0.43，0.27.我想请问一下模型训练是否有一些问题？不进行压缩的时候在5k张openimagev6数据集上的测试结果是0.82，但是压缩之后得出来的结果很差

**Comment by Hongboo-Li** [comment]
0.82是我用训练出来的模型在evaluation模式下执行evaluation_ori测试出来的，应该还是用了压缩增强网络的吧
if self.ori_eval == True:
    outputs = self._evaluation_ori(fname)
else:
    outputs = self._evaluation(fname)

**Comment by Hongboo-Li** [comment]
我觉得应该是ffmpeg转换和vvc压缩的问题，在_evaluation函数里我直接把p2,p3层特征换成原始的p2,p3层特征，精度也能上来，但是奇怪，ffmpeg和vvc这一部分代码我也没修改啥

**Comment by Hongboo-Li** [comment]
您好，我用ffmpeg测试了原始的的特征图和rec重建的特征图的psnr大概在75-79.您的意思是转换前后psnr的值会到100吗？

**Comment by 17-Ranger** [comment]
是的，说明ffmpeg转换的时候有了失真，如果没修改原脚本的话应该是没有问题的，建议好好检查一下。另外这部分代码很久之前写的了有点记不得了，印象中evaluation_ori应该是不加压缩增强网络的，可以看下代码确认下，所以模型也可能没收敛，还是建议用tensorboard看看


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)





 
您好，我用ffmpeg测试了原始的的特征图和rec重建的特征图的psnr大概在75-79.您的意思是转换前后psnr的值会到100吗？

**Comment by Hongboo-Li** [comment]
好的，我再检查一下，谢谢你！

**Comment by Hongboo-Li** [comment]
您好，我后来又看了一下训练过程中的损失变化，确实一直在波动。然后我把学习率改成了10-5去训练，损失倒是降了，但是用这个模型去测试的结果直接约等于是0了，我感觉可能是过拟合了，就好难训

**Comment by Hongboo-Li** [comment]
老哥，这个论文我用来做本科毕设的，能不能找别人帮忙下一下模型，我感觉以我的能力可能训不出来了

**Comment by 17-Ranger** [comment]
好的，我晚上找人找找


------------------ 原始邮件 ------------------
发件人: Li Hongbo ***@***.***&gt;
发送时间: 2024年4月1日 10:33
收件人: 17-Ranger/VCM_DSSLIC ***@***.***&gt;
抄送: 17-Ranger ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)





 
老哥，这个论文我用来做本科毕设的，能不能找别人帮忙下一下模型，我感觉以我的能力可能训不出来了

**Comment by Hongboo-Li** [comment]
您好，还能找到吗

**Comment by 17-Ranger** [comment]
他们这两天正好在修服务器上不去，我今天再问问



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Li Hongbo ***@***.***&gt;
发送时间: 2024年4月4日 11:17
收件人: 17-Ranger/VCM_DSSLIC ***@***.***&gt;
抄送: 17-Ranger ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)





 
您好，还能找到吗

**Comment by 17-Ranger** [comment]
找到了，校外下载速度慢，晚点发你



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Li Hongbo ***@***.***&gt;
发送时间: 2024年4月4日 11:17
收件人: 17-Ranger/VCM_DSSLIC ***@***.***&gt;
抄送: 17-Ranger ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)





 
您好，还能找到吗

**Comment by Hongboo-Li** [comment]
太感谢了

**Comment by 17-Ranger** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 徐涛 ***@***.***&gt;
发送时间: 2024年4月5日 16:56
收件人: 1286998070 ***@***.***&gt;
主题: Fw: model_ICME模型







从buaa.edu.cn发来的超大附件
  
model_ICME.pth  (544MB, 2024年04月12日 16:56 到期)查看下载信息&nbsp;

**Comment by Hongboo-Li** [comment]
似乎有点问题，没有文件也没有下载链接
&nbsp;


李鸿波
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月5日(星期五) 下午4:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)














 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 徐涛 ***@***.***&amp;gt; 
 发送时间: 2024年4月5日 16:56 
 收件人: 1286998070 ***@***.***&amp;gt; 
 主题: Fw: model_ICME模型 
 
 
 
 
 
 
 
 从buaa.edu.cn发来的超大附件 
    
 model_ICME.pth  (544MB, 2024年04月12日 16:56 到期)查看下载信息&amp;nbsp;

**Comment by 17-Ranger** [comment]
估计是github reply的问题，给我个邮箱我直接转发给你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月5日(星期五) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)





 似乎有点问题，没有文件也没有下载链接 
 &amp;nbsp; 
 
 
 李鸿波 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2024年4月5日(星期五) 下午4:58 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1) 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: 徐涛 ***@***.***&amp;amp;gt;  
  发送时间: 2024年4月5日 16:56  
  收件人: 1286998070 ***@***.***&amp;amp;gt;  
  主题: Fw: model_ICME模型  
   
   
   
   
   
   
   
  从buaa.edu.cn发来的超大附件  
      
  model_ICME.pth  (544MB, 2024年04月12日 16:56 到期)查看下载信息&amp;amp;nbsp;

**Comment by Hongboo-Li** [comment]
***@***.***&nbsp;


李鸿波
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月5日(星期五) 下午5:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)














 估计是github reply的问题，给我个邮箱我直接转发给你 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年4月5日(星期五) 下午5:35 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1) 
 
 
 
 
 
  似乎有点问题，没有文件也没有下载链接  
  &amp;amp;nbsp;  
   
   
  李鸿波  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2024年4月5日(星期五) 下午4:58  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)  
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   发自我的iPhone   
     
     
   ------------------ 原始邮件 ------------------   
   发件人: 徐涛 ***@***.***&amp;amp;amp;gt;   
   发送时间: 2024年4月5日 16:56   
   收件人: 1286998070 ***@***.***&amp;amp;amp;gt;   
   主题: Fw: model_ICME模型   
     
     
     
     
     
     
     
   从buaa.edu.cn发来的超大附件   
        
   model_ICME.pth  (544MB, 2024年04月12日 16:56 到期)查看下载信息&amp;amp;amp;nbsp;

**Comment by 17-Ranger** [comment]
我这里收到的全是乱码，你加我微信发我邮箱吧，微信ccr1286998070




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月5日(星期五) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)





 ***@***.***&amp;nbsp; 
 
 
 李鸿波 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2024年4月5日(星期五) 下午5:40 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1) 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  估计是github reply的问题，给我个邮箱我直接转发给你  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2024年4月5日(星期五) 下午5:35  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)  
   
   
   
   
   
   似乎有点问题，没有文件也没有下载链接   
   &amp;amp;amp;nbsp;   
     
     
   李鸿波   
   ***@***.***   
     
     
     
   &amp;amp;amp;nbsp;   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2024年4月5日(星期五) 下午4:58   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)   
     
     
     
     
     
     
     
     
     
     
     
     
     
     
    发自我的iPhone    
       
       
    ------------------ 原始邮件 ------------------    
    发件人: 徐涛 ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2024年4月5日 16:56    
    收件人: 1286998070 ***@***.***&amp;amp;amp;amp;gt;    
    主题: Fw: model_ICME模型    
       
       
       
       
       
       
       
    从buaa.edu.cn发来的超大附件    
          
    model_ICME.pth  (544MB, 2024年04月12日 16:56 到期)查看下载信息&amp;amp;amp;amp;nbsp;

**Comment by Hongboo-Li** [comment]
好
&nbsp;


李鸿波
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月5日(星期五) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)














 我这里收到的全是乱码，你加我微信发我邮箱吧，微信ccr1286998070 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年4月5日(星期五) 下午5:42 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1) 
 
 
 
 
 
  ***@***.***&amp;amp;nbsp;  
   
   
  李鸿波  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2024年4月5日(星期五) 下午5:40  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)  
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   估计是github reply的问题，给我个邮箱我直接转发给你   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "17-Ranger/VCM_DSSLIC"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2024年4月5日(星期五) 下午5:35   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)   
     
     
     
     
     
    似乎有点问题，没有文件也没有下载链接    
    &amp;amp;amp;amp;nbsp;    
       
       
    李鸿波    
    ***@***.***    
       
       
       
    &amp;amp;amp;amp;nbsp;    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: ***@***.***&amp;amp;amp;amp;gt;;     
    发送时间: 2024年4月5日(星期五) 下午4:58    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;     
    抄送: ***@***.***&amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;gt;;     
    主题: Re: [17-Ranger/VCM_DSSLIC] 运行demo.sh的时候需要output/model_mseP1.pth模型文件，请问是否可以提供一下 (Issue #1)    
       
       
       
       
       
       
       
       
       
       
       
       
       
       
     发自我的iPhone     
         
         
     ------------------ 原始邮件 ------------------     
     发件人: 徐涛 ***@***.***&amp;amp;amp;amp;amp;gt;     
     发送时间: 2024年4月5日 16:56     
     收件人: 1286998070 ***@***.***&amp;amp;amp;amp;amp;gt;     
     主题: Fw: model_ICME模型     
         
         
         
         
         
         
         
     从buaa.edu.cn发来的超大附件     
            
     model_ICME.pth  (544MB, 2024年04月12日 16:56 到期)查看下载信息&amp;amp;amp;amp;amp;nbsp;
